### PR TITLE
Fix IL2CPP

### LINKED ISSUE #24: Error decompressing on IL2CPP (Unity)
ZstdSharp fails to decompress when running in IL2CPP build. When using .NET runtime (in Unity Editor), it works, but when building the application with IL2CPP backend, it fails to decompress data, and sometimes causes the application process to crash.

Steps to reproduce:

- Attach this script to any GameObject in scene:

```cs
using System;
using System.IO;
using UnityEngine;

namespace ZstdSharp
{
    public class ZstdTest : MonoBehaviour
    {
        public string[] sampleFileNames = new string[]
        {
            "Zstd_data_1.txt",
            "Zstd_data_2.txt",
        };

        void Start()
        {
            foreach (string sampleFile in this.sampleFileNames)
            {
                Debug.Log($"Testing sample: {sampleFile}");
                var compressed = File.ReadAllBytes(sampleFile).AsSpan();
                using var zstd = new ZstdSharp.Decompressor();
                var decompressed = zstd.Unwrap(compressed);
                Debug.Log($"Decompressed {compressed.Length} -> {decompressed.Length}");
            }
        }
    }
}
```

- Add these 2 files to project folder (next to `Assets` folder) :
	- [Zstd_data_1.txt](https://github.com/oleg-st/ZstdSharp/files/11843537/Zstd_data_1.txt)
	- [Zstd_data_2.txt](https://github.com/oleg-st/ZstdSharp/files/11843538/Zstd_data_2.txt)

- Enter play mode, and files will be decompressed normally (as visible in Console)

- Build and run the project with IL2CPP -> decompression fails -> application will log exceptions to `C:\Users\{User}\AppData\LocalLow\DefaultCompany\{Project name}`

If you need any help to reproduce, let me know.

### PR DESCRIPTION
**Pull request by in0finite**
Fixes #24

### CODE REVIEW

**Comment by oleg-st** [comment]
`#if ENABLE_IL2CPP` will only work at compile time, it will not be present in the assembly. 
So IL2CPP will not have this information when converting from dll to cpp.
You need a separate assembly compiled with this option and type substitutions.

**Comment by in0finite** [comment]
From Unity side, you only need 1 assembly, the one which is compiled with `ENABLE_IL2CPP`. This assembly works both with NET runtime and IL2CPP.

This is currently the only way to make this library work with IL2CPP, so for that reason I would allow this directive to be defined in the library - if not defined, it doesn't change anything in the project.

**Comment by oleg-st** [comment]
Replacing native integer types with 64-bit ones will result in performance degradation on 32-bit platforms.
Besides, it means changing the public API, which may lead to compatibility problems between versions.

For these reasons a fix in Unity is more preferable, until then you can use a separately built library for Unity.

**Comment by oleg-st** [comment]
A Unity fix is coming, so I'll close this.

**Pull request closed without merging**
